displayName=EnchantedSymbolProtector
author=Zachary Jacobson
description=Prevents using the Enchanted Symbol if it would be lost on death
tags=clues,enchanted symbol,ma2,protect item,wildy,wilderness
version=1.0
plugins=com.enchantedsymbolprotector.EnchantedSymbolProtectorPlugin
build=standard